export const events = [
  {
    id: 'F1B4AD8E',
    eventName: 'AIRBORNE',
    eventDescription:
      'Embark on a soaring adventure at Airborne, where innovation takes flight! This event invites participants to design and construct a wireless remote-controlled aircraft powered solely by electric motors, featuring complete control over yaw, pitch, and roll. Unleash your engineering prowess and creativity as you craft a flying marvel capable of navigating three-dimensional movements with precision. Experience the thrill of watching your creation take to the skies, maneuvering through the air with grace and agility. Join fellow enthusiasts in a celebration of aeronautical innovation, where imagination meets engineering to push the boundaries of remote-controlled flight at Airborne!',
    coordinator1: 'Jayant Dadhich',
    coordinator2: 'Afshan Ali',
    coordinator1Mobile: 8955875737,
    coordinator2Mobile: 7300386363,
    prizeMoney: 30000,
    image: 'airbone',
    regFee: 1000,
    isTeam: 'TRUE',
    teamSize: 5,
    rulebook: 'https://drive.google.com/file/d/1wzyssWmGyjKz_S4ukAtlrgJNNLtuEsN0/view?usp=drive_link',
  },
  {
    id: '3FCCFB53',
    eventName: 'ANTOHO',
    eventDescription:
      "Welcome to Anhoto, an event designed to ignite a passion for aerodynamics among students! This engaging competition features three exciting rounds aimed at fostering a deeper understanding of flight principles. In Round 1, participants showcase their knowledge and creativity in the Abstract Round, delving into the theoretical aspects of aerodynamics. Round 2 challenges them to maximize displacement from the launch point, putting their understanding into practical use as they strive for maximum distance. Should there be a draw in Round 2, the thrilling Round 3 awaits, offering an additional challenge to break the tie. Join us for a journey through the skies of knowledge and hands-on experimentation, as Anhoto inspires a new generation's fascination with the science of flight",
    coordinator1: 'Harshwardhan Singh',
    coordinator2: 'Apurva Garg',
    coordinator1Mobile: 8000323536,
    coordinator2Mobile: 6367702141,
    prizeMoney: 8000,
    image: 'antoho',
    regFee: 100,
    isTeam: 'TRUE',
    teamSize: 3,
    rulebook: 'https://drive.google.com/file/d/1B-OLJk3yKdct75syLjN--fqnfz0mGVyG/view?usp=drive_link',
  },
  {
    id: '709CE54D',
    eventName: 'Battle-of-Bids',
    eventDescription:
      'Prepare for the ultimate bidding showdown at the Battle of Bids! This thrilling event transforms the art of auctions into a team-based competition featuring an array of coveted collectible items—from NFTs and fine wines to cricket bats, paintings, and exquisite watches. Equipped with virtual money, each participant becomes a strategic bidder in this electrifying spectacle projected for all to witness. Rally together in teams of 2-4 members, strategize, and outbid your rivals to secure these prized possessions. Engage in the thrill of the auction, showcase your keen eye for value, and experience the adrenaline rush of competitive bidding. Join us for an immersive and exhilarating event that blends strategy, teamwork, and the thrill of acquiring exceptional collectibles at the Battle of Bids!',
    coordinator1: 'Khushi Sharma',
    coordinator2: 'Mansha Raisinghani',
    coordinator1Mobile: 9829702226,
    coordinator2Mobile: 9461507032,
    prizeMoney: 8000,
    image: 'battle-of-bids',
    regFee: 200,
    isTeam: 'TRUE',
    teamSize: 4,
    rulebook: 'https://drive.google.com/file/d/12YZwTm7GLctb43isbvhpV-ivtPJV0knt/view?usp=drive_link',
  },
  {
    id: '9DC56E5A',
    eventName: 'Business Buzz',
    eventDescription:
      "Welcome to 'Business Buzz,' where spontaneity meets teamwork! This engaging event challenges your quick thinking while emphasizing seamless coordination within your team. Get ready for an exciting journey filled with spontaneous questions that blend fun with informative insights into new businesses, startups, and business mergers. Sharpen your ability to think on your feet as you navigate through a dynamic exchange of knowledgeable information. Join us for an interactive experience where learning meets enjoyment, offering valuable insights into the ever-evolving landscape of entrepreneurship and corporate ventures. Embrace the challenge, foster teamwork, and revel in the thrill of Business Buzz!",
    coordinator1: 'Ashish Singh',
    coordinator2: 'Mukul Dhakkad',
    coordinator1Mobile: 7014627723,
    coordinator2Mobile: 9413653797,
    prizeMoney: 5000,
    image: 'bussinessbuzz',
    regFee: 200,
    isTeam: 'TRUE',
    teamSize: 4,
    rulebook: 'https://drive.google.com/file/d/1Ae4p0X1YS-X3ybrtPa3Y06fCOuKsLvZa/view?usp=drive_link',
  },
  {
    id: 'D0099AB0',
    eventName: 'Cadovation',
    eventDescription:
      "Get ready for CADOVATION, an event crafted by the Master Builder's Club of Rajasthan Technical University to unleash your creativity and skill in an exhilarating competition! Join us in a thrilling test of creativity, response time, and pressure handling using the renowned software 'AUTOCAD.' This event promises a fun yet challenging experience, where participants' caliber will be put to the test through innovative design challenges. Whether you're a seasoned designer or new to CAD software, CADOVATION offers an exciting platform to showcase your talents, navigate through challenges, and craft solutions under pressure. Join us for an event that blends fun and skill, pushing the boundaries of design excellence!",
    coordinator1: 'Sourabh Sharma',
    coordinator2: 'Mohit Sen',
    coordinator1Mobile: 8619787050,
    coordinator2Mobile: 6350631677,
    prizeMoney: 6000,
    image: 'cadovation',
    regFee: 100,
    isTeam: 'FALSE',
    teamSize: 1,
    rulebook: 'https://drive.google.com/file/d/1hgfCSM5_HlqpPfK9G7533JvdT7JXWO_Z/view?usp=drive_link',
  },
  {
    id: '012E23DE',
    eventName: 'Cybrog Trench',
    eventDescription:
      "Step into the future with Cyborg Trench, an event that merges innovation and robotics! Join us as we witness the ultimate showdown with pick-and-place bots equipped with precision clamper arms. These bots face the challenge of picking objects and navigating through obstacles to place them at designated spots. Feel the excitement as these machines showcase their agility and intelligence, overcoming hurdles and showcasing their precision. It's a thrilling display of technology meeting strategy as these cyborgs clear paths and accomplish tasks with incredible accuracy. Join us for a day of futuristic feats and witness the power of robotics in action at Cyborg Trench",
    coordinator1: 'Ashwin Kothiya',
    coordinator2: 'Ishan Kaushik',
    coordinator1Mobile: 9166942632,
    coordinator2Mobile: 9166942632,
    prizeMoney: 17000,
    image: 'cyborgtrench',
    regFee: 500,
    isTeam: 'TRUE',
    teamSize: 4,
    rulebook: 'https://drive.google.com/file/d/1DGwLx00i38wHd0qCKTKWdQGoq__INngN/view?usp=drive_link',
  },
  {
    id: '70663E81',
    eventName: 'GAME OF DRONES',
    eventDescription:
      "Welcome to the high-flying competition of skill and innovation at the Game of Drones! This event invites students from all departments, irrespective of their branch or year of study, to showcase their prowess in building and piloting quadcopters. Dive into the world of aerial mechanics where teams will craft quadcopters, navigating them from source to destination through a challenging obstacle course. Whether you're a novice or an expert, this competition tests your engineering skills and teamwork in maneuvering these agile flying machines. Join us for an electrifying event where creativity meets technology, and witness the thrill of overcoming hurdles with precision and teamwork in the exhilarating Game of Drones!",
    coordinator1: 'Tanisha Pareta',
    coordinator2: 'Sachin Soni',
    coordinator1Mobile: 6376213897,
    coordinator2Mobile: 7599026707,
    prizeMoney: 25000,
    image: 'gameofdrones',
    regFee: 1000,
    isTeam: 'TRUE',
    teamSize: 4,
    rulebook: 'https://drive.google.com/file/d/1WRh0uUEMPkKXfHZnevC3zyeQ9T8LXgZM/view?usp=drive_link',
  },
  {
    id: '49DA7402',
    eventName: 'Hoverstorm',
    eventDescription:
      "Prepare for the thrilling challenge of HoverStorm! In this competition, teams will design and construct remote-controlled, wireless hovercrafts capable of conquering various terrains—be it land, water, grassy patches, or inclines. The path promises an adventure-filled track featuring diverse surfaces and obstacles. Each team's task? Craft a lightweight, agile, and durable hovercraft capable of outperforming opponents in races and challenges. The competition's judgment is based on maximum stay duration—showcasing strength, agility, and endurance as hovercrafts aim to outlast their rivals. Join us for an adrenaline-fueled event where innovation meets adventure, and witness the excitement as these hovercrafts defy limits to claim victory in the ultimate HoverStorm challenge!",
    coordinator1: 'Narendra Meena',
    coordinator2: 'Bhawana',
    coordinator1Mobile: 9981473226,
    coordinator2Mobile: 8905158169,
    prizeMoney: 15000,
    image: 'hoverstorm',
    regFee: 750,
    isTeam: 'TRUE',
    teamSize: 5,
    rulebook: 'https://drive.google.com/file/d/1_pRmRJy92dtNPqtb6iZx7JbO6Wmo84wi/view?usp=drive_link',
  },
  {
    id: '63E44E48',
    eventName: 'Mindscape Rumble',
    eventDescription:
      "Welcome to MindScape Rumble, where fun meets skill-building in an immersive event designed to elevate your cognitive prowess! Engage in a series of mind-bending challenges crafted to boost your thinking power and problem-solving abilities. Navigate through intriguing obstacles that challenge your intellect and creativity while enjoying an atmosphere filled with excitement and enjoyment. Whether you're passionate about puzzles, strategic games, or simply seeking to enhance your cognitive abilities, MindScape Rumble offers an exhilarating experience that promises both mental stimulation and a whole lot of fun. Join us for a day of brain-boosting adventures and unleash the power of your mind in this thrilling and enjoyable event!",
    coordinator1: 'Rohit Meena',
    coordinator2: 'Kavita Sehra',
    coordinator1Mobile: 9694492169,
    coordinator2Mobile: 8302808490,
    prizeMoney: 5000,
    image: 'mindscaperumble',
    regFee: 150,
    isTeam: 'TRUE',
    teamSize: 3,
    rulebook: 'https://drive.google.com/file/d/1ab6C_dERq2BQ9nZrjSdmiYedchUcXJXg/view?usp=drive_link',
  },
  {
    id: 'CE281413',
    eventName: 'MOBA (multiplayer online battle arena) : \nBGMI',
    eventDescription:
      "Multiplayer online battle arena (MOBA)is a subgenre of strategy video games in which two teams of players compete against each other on a predefined battlefield. Each player controls a single character with a set of distinctive abilities that improve over the course of a game and which contribute to the team's overall strategy. The typical ultimate objective is for each team to destroy their opponents' main structure, located at the opposite corner of the battlefield. In some MOBA games, the objective can be defeating every player on the enemy team. Players are assisted by computer-controlled units that periodically spawn in groups and march forward along set paths toward their enemy's base, which is heavily guarded by defensive structures. This type of multiplayer online video games originated as a subgenre of real-time strategy",
    coordinator1: 'Bhuvnesh Meena',
    coordinator2: 'Ashutosh Sharma',
    coordinator1Mobile: 9636952506,
    coordinator2Mobile: 8094240640,
    prizeMoney: 10000,
    image: 'moba-bgmi',
    regFee: 200,
    isTeam: 'TRUE',
    teamSize: 4,
    rulebook: 'https://drive.google.com/file/d/1kdoxTm4h9-KqL5upqGere_OH0czSiokE/view?usp=drive_link',
  },
  {
    id: '72ADF80D',
    eventName: 'MOBA (multiplayer online battle arena) : VALORANT',
    eventDescription:
      'MOBA-Valorant is the apex of competitive Valorant gaming, uniting elite global teams in a high-stakes battleground. This spectacle showcases precision, strategy, and teamwork as top-tier players unleash agent abilities and flawless tactics. From grand arenas to global streams, it mesmerizes audiences with intense clashes, strategic brilliance, and heart-stopping plays. The event unites the Valorant community in a celebration of skill and sportsmanship. As teams vie for victory, the tournament builds towards a climactic showdown, defining new esports legends and leaving an indelible mark on the gaming world. MOBA-Valorant epitomizes the pinnacle of competitive gaming, crafting unforgettable moments in the annals of esports history.',
    coordinator1: 'Bhuvnesh Meena',
    coordinator2: 'Ashutosh Sharma',
    coordinator1Mobile: 9636952506,
    coordinator2Mobile: 8094240640,
    prizeMoney: 10000,
    image: 'moba-valorant',
    regFee: 300,
    isTeam: 'TRUE',
    teamSize: 5,
    rulebook: 'https://drive.google.com/file/d/1OGEZQ4inD2Qr-yPniUFbzm7Co5_o9xsx/view?usp=drive_link',
  },
  {
    id: '33B59EE6',
    eventName: 'Model United Nations (MUN)',
    eventDescription:
      'Model United Nations (MUN) is an educational simulation program where students, typically in high school or college, role-play as delegates representing various countries in a simulated United Nations conference. Participants engage in debates, negotiations, and resolutions on global issues, aiming to find diplomatic solutions to real-world problems such as climate change, international conflicts, and human rights. MUN fosters critical thinking, research skills, public speaking, and an understanding of international affairs. It provides a platform for young people to develop their knowledge of diplomacy and global politics while promoting teamwork and multicultural understanding. MUN conferences occur worldwide, promoting collaboration and diplomacy among future leaders',
    coordinator1: 'Govind Madaan',
    coordinator2: 'Anushriya Roy',
    coordinator1Mobile: 9602810361,
    coordinator2Mobile: 8287571185,
    prizeMoney: 50000,
    image: 'mun',
    regFee: 1200,
    isTeam: 'FALSE',
    teamSize: 1,
    rulebook: 'https://drive.google.com/file/d/17YeIVzZl3ltVOfAcxKhxqclffEaSpWEz/view?usp=drive_link',
  },
  {
    id: '80A3A948',
    eventName: 'RC NITRO',
    eventDescription:
      "Rev up your engines for the heart-pounding RC Nitro Championship! Experience the adrenaline rush of scaled car and buggy racing at its finest, with powerful 1:10 and 1:8 models fueled by nitro-based adrenaline. Feel the thrill as these miniature beasts tear up the track with incredible speed and precision. Whether you're a seasoned racer or a newcomer to the RC world, this championship promises high-octane excitement, intense competition, and roaring engines. Join us for a day of exhilarating races, nail-biting moments, and the chance to showcase your skills in the electrifying world of RC Nitro racing",
    coordinator1: 'Arpit Pareta',
    coordinator2: 'Abhijeet Bhuwalia',
    coordinator1Mobile: 9001174873,
    coordinator2Mobile: 8079037704,
    prizeMoney: 50000,
    image: 'rcnitro',
    regFee: 1000,
    isTeam: 'TRUE',
    teamSize: 6,
    rulebook: '',
  },
  {
    id: '8F39B429',
    eventName: 'ROBO-WAR 15KG',
    eventDescription:
      "Welcome to the adrenaline-pumping battlefield of Robo-War! In this event, participants craft and unleash their innovative genius by designing and constructing remote-controlled or autonomous robots primed for simulated combat. These mechanical gladiators are armed with an array of offensive and defensive weaponry, armor, and maneuverability features. Engage in intense showdowns as these robots clash in simulated battles, displaying tactical prowess, resilience, and technological prowess. Whether you're a mastermind in robotics or a newcomer to engineering marvels, Robo-War offers an electrifying platform to witness the ultimate clash of machines. Join us for a riveting spectacle where creativity meets combat, and witness the epic battles unfold in this thrilling Robo-War event!",
    coordinator1: 'Dishantar Jangid',
    coordinator2: '',
    coordinator1Mobile: 6378464482,
    coordinator2Mobile: '',
    prizeMoney: 200000,
    image: 'robowar',
    regFee: 1500,
    isTeam: 'TRUE',
    teamSize: 6,
    rulebook: '',
  },
  {
    id: 'FD40EE2B',
    eventName: 'ROBO-WAR 30KG',
    eventDescription:
      "Welcome to the adrenaline-pumping battlefield of Robo-War! In this event, participants craft and unleash their innovative genius by designing and constructing remote-controlled or autonomous robots primed for simulated combat. These mechanical gladiators are armed with an array of offensive and defensive weaponry, armor, and maneuverability features. Engage in intense showdowns as these robots clash in simulated battles, displaying tactical prowess, resilience, and technological prowess. Whether you're a mastermind in robotics or a newcomer to engineering marvels, Robo-War offers an electrifying platform to witness the ultimate clash of machines. Join us for a riveting spectacle where creativity meets combat, and witness the epic battles unfold in this thrilling Robo-War event!",
    coordinator1: 'Dishantar Jangid',
    coordinator2: '',
    coordinator1Mobile: 6378464482,
    coordinator2Mobile: '',
    prizeMoney: 200000,
    image: 'robowar',
    regFee: 2000,
    isTeam: 'TRUE',
    teamSize: 6,
    rulebook: 'https://drive.google.com/file/d/1RCo5fsL4VAycOSFDpvi1MTY8oP32aIXU/view?usp=drive_link',
  },
  {
    id: '8F87AD58',
    eventName: 'Robo Race',
    eventDescription:
      'Gear up for the ultimate test of speed and innovation at RoboRace! This competition challenges participants to design and construct their custom robots—wired or wireless—within specific dimensions, aiming to achieve maximum speed and outpace rival robots on a designated track. The goal? Reach the finish line in record time by navigating varied terrains and obstacles without deviating from the track. Craft a manually controlled robot with the agility and resilience to conquer hurdles and diverse surfaces. Robots with the fastest times progress to subsequent rounds, culminating in a thrilling showdown where the swiftest and most agile bot emerges victorious. Join us for a high-speed spectacle where ingenuity meets competition in the exhilarating RoboRace!',
    coordinator1: 'Mohd Muzammil',
    coordinator2: 'Somil Jain',
    coordinator1Mobile: 6350132878,
    coordinator2Mobile: 6376114339,
    prizeMoney: 17000,
    image: 'roborace',
    regFee: 500,
    isTeam: 'TRUE',
    teamSize: 4,
    rulebook: 'https://drive.google.com/file/d/1msuNSMqBBcg3JZndnFVYP9BX7S-dt7dO/view?usp=drive_link',
  },
  {
    id: 'C9273E60',
    eventName: 'Robo Soccer',
    eventDescription:
      'In the realm of robotic sports, Robo Soccer reigns as the pinnacle of intensity and renown. Wireless or wired bots dash across expansive arenas, vying to outscore their rivals in a thrilling display. This event serves as a catalyst for young minds, urging them to tackle robotic hurdles, craft innovative bots, and delve into STEM fields. Bot design becomes an enriching journey for students, fostering enjoyment, teamwork, and organic learning experiences. Robo Soccer stands as a testament to the fusion of fun, collaborative effort, and natural education, empowering the next generation through the excitement of robotics.',
    coordinator1: 'Athar Raza',
    coordinator2: 'Mohammad',
    coordinator1Mobile: 9636596242,
    coordinator2Mobile: 8824707193,
    prizeMoney: 25000,
    image: 'robosoccer',
    regFee: 700,
    isTeam: 'TRUE',
    teamSize: '',
    rulebook: '',
  },
  {
    id: '3D1B30E9',
    eventName: 'Robo Sumo',
    eventDescription:
      'Enter the ring for the electrifying showdown of Robo Sumo Wrestling! This exhilarating sport pits two robots, known as sumobots, against each other in a battle of strength and strategy. Mirroring the principles of sumo wrestling, these bots aim to push, maneuver, and outwit their opponent, attempting to force them out of the designated circle. Crafted with precision and designed for agility, these sumobots engage in a thrilling contest where strategy, maneuverability, and raw power determine the victor. Join us for an action-packed event where technology meets the ancient art of sumo, as these robotic contenders clash for supremacy in the exciting world of Robo Sumo Wrestling',
    coordinator1: 'Jay Singor',
    coordinator2: 'Riya Suthar',
    coordinator1Mobile: 9166588624,
    coordinator2Mobile: 8769465670,
    prizeMoney: 25000,
    image: 'robosumo',
    regFee: 500,
    isTeam: 'TRUE',
    teamSize: 4,
    rulebook: 'https://drive.google.com/file/d/18sN0W0_Uup-T5uWmWZb-jXv9dayY6rZw/view?usp=drive_link',
  },
  {
    id: 'E393A5A0',
    eventName: 'SEISMOSHIELD CHALLENGE',
    eventDescription:
      'Welcome to Shishmo-Shield, an innovative competition challenging engineers, architects, and students to pioneer earthquake-resistant structures! Participants will showcase their talents and originality by designing and constructing avant-garde buildings capable of withstanding simulated seismic pressures. With the aim of promoting earthquake-resistant infrastructure and material innovation, this competition fosters awareness and collaboration among diverse backgrounds. Rules dictate the creation of models or prototypes using any construction materials provided, emphasizing safety measures during construction. Entries will undergo evaluation based on their ability to resist seismic forces, creativity, and overall design. Projects will face rigorous testing through simulated seismic forces, with judges assessing structural integrity and innovation. Join us in this quest for resilient structures that redefine safety and innovation in the face of seismic challenges at Shishmo-Shield!',
    coordinator1: 'Prachi Soni',
    coordinator2: 'Lokesh Chouhan',
    coordinator1Mobile: 8278649629,
    coordinator2Mobile: 7062305851,
    prizeMoney: 12000,
    image: 'seismoshield',
    regFee: 300,
    isTeam: 'FALSE',
    teamSize: 1,
    rulebook: 'https://drive.google.com/file/d/1fMGQhQq4JfLgzMwrwT9Kyr1TnfqvXEgl/view?usp=drive_link',
  },
  {
    id: '3D542373',
    eventName: 'Strength-o-mania',
    eventDescription:
      "Strength o' Mania, a rigorous challenge, evaluates structural stability. Focused on bridge building and cement ball construction, it beckons teams impassioned by mechanics. Participants design a model bridge and craft a cement ball, both undergoing rigorous tests. The climax demands the bridge support weight while the ball navigates unscathed to its destination. Success rests on meticulous design and construction prowess. This event showcases engineering finesse, demanding teams merge innovation with durability. Strength o' Mania stands as a proving ground, challenging competitors to uphold strength and precision in construction, culminating in a display of resilience and craftsmanship.",
    coordinator1: 'Pragya Prajapati',
    coordinator2: 'Nikhil Mehra,',
    coordinator1Mobile: 9928059030,
    coordinator2Mobile: 8955655478,
    prizeMoney: 13000,
    image: 'strengthomania',
    regFee: 300,
    isTeam: 'TRUE',
    teamSize: 3,
    rulebook: 'https://drive.google.com/file/d/1FWaEQ3-wJRVEKe6F1iIRxt5y7j8FN7Xp/view?usp=drive_link',
  },
  {
    id: '16EE61FF',
    eventName: 'TGKC-THAR GO KART CHAMPIONSHIP',
    eventDescription:
      'Welcome to the thrill-packed THAR Go-Kart Championship (TGKC), where speed meets engineering finesse! A go-kart, synonymous with high-speed racing, takes the center stage in this event, representing the epitome of four-wheeled motor prowess. From recreational to high-performance racing models, go-karts are compact, lightweight vehicles designed for motorsport training or adrenaline-pumping racing experiences. The TGKC presents a series of challenging rounds including design, business, skid pad, auto cross, and an ultimate test of endurance. Participants will showcase their innovation in design, business acumen, maneuverability on the track, and stamina in a rigorous endurance challenge. Join us for a race-packed event that celebrates the spirit of motorsports and engineering brilliance at the THAR Go-Kart Championship!',
    coordinator1: 'Rohit Meena',
    coordinator2: 'Rohit Kumar Meena',
    coordinator1Mobile: 8947918350,
    coordinator2Mobile: 6378292905,
    prizeMoney: 200000,
    image: 'tgkc',
    regFee: 15000,
    isTeam: 'TRUE',
    teamSize: 30,
    rulebook: 'https://drive.google.com/file/d/1eizXZ0CBvwQDpGOp-zJE1tx2juMsJkck/view?usp=drive_link',
  },
  {
    id: '9320BF9F',
    eventName: 'TharVista',
    eventDescription:
      "Indulge your visual senses in TharVista, an enticing food photography competition that celebrates the artistry of culinary delight! This competition invites participants to capture the essence and allure of the culinary world through their lens. Whether it's the vibrant colors, intricate details, or sumptuous textures, showcase the tantalizing beauty of gastronomy in stunning visuals. From the sizzle of a skillet to the intricacies of plated delicacies, TharVista aims to capture the essence of food in all its glory. Join us for a visual feast that celebrates the art of food through photography, where every snapshot tells a flavorful story at TharVista!",
    coordinator1: 'Deepak Maurya',
    coordinator2: 'Kanishk Rao',
    coordinator1Mobile: 8504819377,
    coordinator2Mobile: 9636882043,
    prizeMoney: 5000,
    image: 'tharvista',
    regFee: 50,
    isTeam: 'FALSE',
    teamSize: 1,
    rulebook: '',
  },
  {
    id: 'FCF1E338',
    eventName: 'THE-FIN-QUEST',
    eventDescription:
      'Welcome to The-Fin-Quest, a three-round journey that immerses you in the depths of financial knowledge! This thrilling event challenges your finance acumen through a series of engaging rounds. First up, flex your mental muscles with a crossword or word search to decipher financial jargon. Next, brace yourself for the rapid-fire and buzzer round, where quick thinking and reflexes are your allies. Finally, put your presentation skills to the test as you showcase comprehensive financial insights. From decoding puzzles to rapid responses and polished presentations, The-Fin-Quest offers a multifaceted platform to demonstrate your financial expertise. Join us for an intellectually stimulating event that pushes the boundaries of financial knowledge to the fullest!',
    coordinator1: 'Tanish Jangid',
    coordinator2: 'Aditya Shekhawat',
    coordinator1Mobile: 8306266889,
    coordinator2Mobile: 6375588128,
    prizeMoney: 8000,
    image: 'thefinquest',
    regFee: 200,
    isTeam: 'TRUE',
    teamSize: 4,
    rulebook: 'https://drive.google.com/file/d/1fJlmJUtUit8j_tw5UoYseKVQ_kSR0GlO/view?usp=drive_link',
  },
  {
    id: '8E6BD50B',
    eventName: 'Track O`Mania',
    eventDescription:
      "Step into the realm of precision and automation with Track O’ Mania, a thrilling line follower event! In this competition, autonomous robots take center stage, showcasing their ability to navigate a defined path. The challenge is simple yet intricate—design a robot capable of following a black line on a white surface, or vice versa, with precision and accuracy. These bots must adeptly detect the designated line and persistently pursue it until reaching the end. It's a test of programming, sensors, and engineering finesse as these autonomous marvels exhibit their ability to stay on course. Join us for an event that celebrates precision, innovation, and the art of robotic navigation at Track O’ Mania!",
    coordinator1: 'Laxmi Kumari',
    coordinator2: 'Jitendra Goswami',
    coordinator1Mobile: 9950855563,
    coordinator2Mobile: 8000590095,
    prizeMoney: 17000,
    image: 'trackomania',
    regFee: 500,
    isTeam: 'TRUE',
    teamSize: 4,
    rulebook: 'https://drive.google.com/file/d/1iB4zTcaxrXvRo52zs2Ju9szsXA_FQL-p/view?usp=drive_link',
  },
  {
    id: 'F2D8CB2E',
    eventName: 'Trader Of The Year',
    eventDescription:
      "Join us for the ultimate trading challenge in the 'Trader Of the Year' event! Dive into a thrilling virtual trading competition where your strategic prowess and market acumen will be put to the test. But here's the twist - embark on an exhilarating treasure hunt alongside trading tasks to unlock hidden clues and bonuses. Navigate through markets, make shrewd decisions, and hunt for treasures that enhance your trading edge. Whether you're a seasoned trader or a novice, this event promises excitement, surprises, and the chance to claim the title of 'Trader Of the Year.' Get ready to trade, strategize, and uncover treasures in this unique and electrifying competition!",
    coordinator1: 'Anil Saini',
    coordinator2: 'Gaurav Purohit',
    coordinator1Mobile: 7378157151,
    coordinator2Mobile: 8740974566,
    prizeMoney: 10000,
    image: 'traderoftheyear',
    regFee: 0,
    isTeam: 'FALSE',
    teamSize: 1,
    rulebook: 'https://drive.google.com/file/d/1zDsp6aaO2ffRCNbEoTi7nnQjLYvXayo8/view?usp=drive_link',
  },
  {
    id: '4C8172C8',
    eventName: 'Treasure hunt',
    eventDescription:
      "Welcome to THAR's Treasure Hunt, an exhilarating quest for hidden riches! Whether it's uncovering sunken shipwrecks or discovering buried cultural relics, this event captures the spirit of adventure. Participants embark on a physical search, seeking treasure in simulated sunken shipwrecks or buried ancient sites. Delve into the thrill of the hunt, solving clues, deciphering puzzles, and exploring diverse landscapes in a quest for hidden treasures. It's not just a game; it's an immersive experience that brings out the inner explorer in each participant. Join us for an adventure-filled journey, where excitement and discovery await at THAR's Treasure Hunt!",
    coordinator1: 'Yadvendra kumar meena',
    coordinator2: 'Neel bhatnagar',
    coordinator1Mobile: 8218836508,
    coordinator2Mobile: 6376914374,
    prizeMoney: 7000,
    image: 'treasurehunt',
    regFee: 0,
    isTeam: 'TRUE',
    teamSize: 5,
    rulebook: 'https://drive.google.com/file/d/1meXbLMMcS6L6ASa7160TL0v4vFHDWaEI/view?usp=drive_link',
  },
  {
    id: 'BAD8D49D',
    eventName: 'Tug of War',
    eventDescription:
      "Prepare for an intense robotic showdown in Tug of War! This competition challenges participants to design and construct either a wired or wireless robot within specified dimensions. These manually operated bots aim to pull their opponent towards their side of the arena, navigating hurdles to earn points along the way. The more hurdles they overcome while pulling their adversary, the more points they accumulate. It's a battle of strength, strategy, and maneuverability as these bots engage in a gripping tug of war. The bot that outmaneuvers, pulls with maximum force, and earns the highest points emerges victorious. Join us for an adrenaline-fueled clash where innovation and robotic prowess meet head-on in the exhilarating Tug of War!",
    coordinator1: 'Himanshu Agarwal',
    coordinator2: 'Mohit Rathore',
    coordinator1Mobile: 9521377501,
    coordinator2Mobile: 9315772565,
    prizeMoney: 16000,
    image: 'tugofwar',
    regFee: 500,
    isTeam: 'TRUE',
    teamSize: 4,
    rulebook: 'https://drive.google.com/file/d/1nOgMBT2L-9u_ngYw8nhXVHUZk_HbzHn3/view?usp=drive_link',
  },
  {
    id: 'A5FC8444',
    eventName: 'Vlogfest',
    eventDescription:
      "Get ready to celebrate the art of storytelling through the lens at VlogFest! This vlogging competition, hosted by Thar, invites participants to showcase their cinematic prowess and storytelling skills. Capture the essence of life's moments, adventures, or perspectives in a compelling vlog that engages and captivates the audience. Whether it's travel escapades, personal anecdotes, or social commentary, unleash your creativity to present a unique narrative perspective that resonates with viewers. Join us for a celebration of creativity and storytelling as you embark on a journey to share your compelling stories through the powerful medium of vlogging at VlogFest!",
    coordinator1: 'Deepak Maurya',
    coordinator2: 'Kanishk Rao',
    coordinator1Mobile: 8504819377,
    coordinator2Mobile: 9636882043,
    prizeMoney: 8000,
    image: 'vlogfest',
    regFee: 70,
    isTeam: 'FALSE',
    teamSize: 1,
    rulebook: 'https://drive.google.com/file/d/1CWLMCL2BaL59L08Tb9xGOps-EPoBkgQi/view?usp=drive_link',
  },
]
